spring.application.name=GoodFiction
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${PGPass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.ai.google.genai.api-key=${GeminiAPIKey}

spring.ai.google.genai.project-id=good-fiction-app
spring.ai.google.genai.location=us-central1

spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.2

google.books.api-key=${GoodFictionAPiKey}
google.books.base-url=https://www.googleapis.com/books/v1/volumes

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true